version: '2.3'
services:
  train_yolox:
    volumes:
      # mount dataset
      - ./datasets:/YOLOX/datasets
      - ./checkpoints:/YOLOX/checkpoints
      - ./model/YOLOX_outputs:/YOLOX/YOLOX_outputs
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 16000000000 # ~16gb
    build:
      context: .
      dockerfile: Dockerfile
      #shm_size: '32gb'
    container_name: train_yolox_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: python /YOLOX/tools/train.py -f /YOLOX/exps/example/custom/yolox_s.py -d 1 -b 16 --fp16 -o -c /YOLOX/checkpoints/yolox_s.pth
    privileged: true