version: '2.3'
services:
  train_yolox:
    volumes:
      # mount dataset
      - ./datasets:/YOLOX/datasets/COCO
    build:
      context: .
      dockerfile: Dockerfile
    container_name: train_yolox_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: nvidia-smi
    privileged: true