name: "Build kicad image action"
description: "Build Kicad docker image for circuit development"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/kicad
        file: ./.github/workflows/docker/kicad/Dockerfile
        tags: wamvtan/kicad:9.0
        no-cache: false
        cache-from: type=registry,ref=wamvtan/kicad:buildcache
        cache-to: type=registry,ref=wamvtan/kicad:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/kicad
        file: ./.github/workflows/docker/kicad/Dockerfile
        tags: wamvtan/kicad:9.0
        no-cache: false
        cache-from: type=registry,ref=wamvtan/kicad:buildcache
        push: false
    - uses: peter-evans/dockerhub-description@v3
      if: ${{ github.event_name == 'pull_request'}}
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        repository: wamvtan/kicad
        short-description: "Docker Image for Virtual RobotX Challenge"
        readme-filepath: ./.github/workflows/docker/kicad/README.md
        enable-url-completion: true
