kibot:
  version: 1

preflight:
  erc: true
  drc: true
  update_xml: true

outputs:
  - name: print schematic
    type: svg_sch_print
    dir: /workspace/schematics
  - name: print pcb
    type: pcb_print
    dir: /workspace/pcb
    options:
      format: SVG
      pages:
      - layers:
        - layer: F.Cu
        - layer: F.Mask
          color: '#14332440'
        - layer: F.Paste
        - layer: F.Silkscreen
        - layer: Edge.Cuts
        - layer: User.Comments
        sheet: Front copper
      - layers:
        - layer: B.Cu
        - layer: B.Mask
          color: '#14332440'
        - layer: B.Silkscreen
        - layer: Edge.Cuts
        - layer: User.Comments
        mirror: true
        sheet: Bottom copper
      - layers:
        - layer: B.Courtyard
        - layer: Edge.Cuts
        - layer: User.Comments
        mirror: true
        sheet: Bottom courtyard area
      - layers:
        - layer: F.Courtyard
        - layer: Edge.Cuts
        - layer: User.Comments
        sheet: Front courtyard area
      - layers:
        - layer: B.Fab
        - layer: Edge.Cuts
        - layer: User.Comments
        mirror: true
        sheet: Bottom documentation
      - layers:
        - layer: F.Fab
        - layer: Edge.Cuts
        - layer: User.Comments
        sheet: Front documentation
      keep_temporal_files: true
      add_background: true
  - name: renderer_for_present
    comment: Renderer for the presentation
    type: pcbdraw
    dir: /workspace/render
  - name: output gerber
    type: gerber
    dir: /workspace/gerber
  - name: output drill file
    type: excellon
    dir: /workspace/drill
  - name: output Interactive HTML BoM
    type: ibom
    options:
      extra_fields: Datasheet
      show_fields: Value,Footprint,Datasheet
      group_fields: Value,Footprint,Datasheet
      extra_data_file: "%F.xml"
    dir: /workspace/bom
  - name: output CSV BoM
    type: bom
    options:
      format: XML
    dir: /workspace/bom
  - name: Make zipfile of the gerber and drill file.
    type: compress
    dir: /workspace/zip
    options:
      format: ZIP
      output: 'gerber_and_drill.zip'
      files:
        - source: '/workspace/gerber/*.gbr'
        - source: '/workspace/gerber/*.drl'
        - source: '/workspace/drill/*.gbr'
        - source: '/workspace/drill/*.drl'
