pre_cmd:
  - pip install InteractiveHtmlBom

# Symbol libraries
# symbol_libs:
#   - path: "/path/to/your/symbol/library.lib"
#   - path: "/another/path/to/symbol/library.lib"

# # Footprint libraries
# footprint_libs:
#   - path: "/path/to/your/footprint/library.pretty"
#   - path: "/another/path/to/footprint/library.pretty"
