/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__HARDWARE_COMMUNICATION_MSGS__HEARTBEAT_PROTO_HARDWARE_COMMUNICATION_MSGS__HEARTBEAT_PB_H_INCLUDED
#define PB_PROTOLINK__HARDWARE_COMMUNICATION_MSGS__HEARTBEAT_PROTO_HARDWARE_COMMUNICATION_MSGS__HEARTBEAT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat {
    uint64_t sequence;
} protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_init_default {0}
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_sequence_tag 1

/* Struct field encoding specification for nanopb */
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   sequence,          1)
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_CALLBACK NULL
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_DEFAULT NULL

extern const pb_msgdesc_t protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_fields &protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_msg

/* Maximum encoded size of messages (where known) */
#define PROTOLINK__HARDWARE_COMMUNICATION_MSGS__HEARTBEAT_PROTO_HARDWARE_COMMUNICATION_MSGS__HEARTBEAT_PB_H_MAX_SIZE protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_size
#define protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
