/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__HARDWARE_COMMUNICATION_MSGS__GROUNDSTATIONHEARTBEAT_PROTO_HARDWARE_COMMUNICATION_MSGS__GROUNDSTATIONHEARTBEAT_PB_H_INCLUDED
#define PB_PROTOLINK__HARDWARE_COMMUNICATION_MSGS__GROUNDSTATIONHEARTBEAT_PROTO_HARDWARE_COMMUNICATION_MSGS__GROUNDSTATIONHEARTBEAT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat {
    uint64_t sequence;
    uint32_t mode;
} protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_init_default {0, 0}
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_sequence_tag 1
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_mode_tag 2

/* Struct field encoding specification for nanopb */
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   sequence,          1) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              2)
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_CALLBACK NULL
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_DEFAULT NULL

extern const pb_msgdesc_t protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_fields &protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_msg

/* Maximum encoded size of messages (where known) */
#define PROTOLINK__HARDWARE_COMMUNICATION_MSGS__GROUNDSTATIONHEARTBEAT_PROTO_HARDWARE_COMMUNICATION_MSGS__GROUNDSTATIONHEARTBEAT_PB_H_MAX_SIZE protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_size
#define protolink__hardware_communication_msgs__GroundStationHeartBeat_hardware_communication_msgs__GroundStationHeartBeat_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
