/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/hardware_communication_msgs__HeartBeat.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat, protolink__hardware_communication_msgs__HeartBeat_hardware_communication_msgs__HeartBeat, AUTO)



