name: "Build WAM-V image action"
description: "Build WAM-V docker images"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true
  module:
    description: "Software module"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/wamv
        file: ./.github/workflows/docker/wamv/Dockerfile
        tags: wamvtan/wamv_${{ inputs.module }}:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/wamv_${{ inputs.module }}:buildcache
        cache-to: type=registry,ref=wamvtan/wamv_${{ inputs.module }}:buildcache,mode=max
        push: true
        platforms: linux/arm64/v8
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/wamv
        file: ./.github/workflows/docker/wamv/Dockerfile
        tags: wamvtan/wamv_${{ inputs.module }}:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/wamv_${{ inputs.module }}:buildcache
        push: false
        platforms: linux/arm64/v8
