services:
  # mqtt_endpoint:
  #   image: wamvtan/mqtt_endpoint:latest
  #   network_mode: host
  #   restart: always
  udp_forward_right_motor:
    image: wamvtan/mqtt_endpoint:latest
    network_mode: host
    restart: always
    command: ["uv", "run", "udp_forward", "192.168.0.101", "8888", "--listen_port", "9001"]
  udp_forward_left_motor:
    image: wamvtan/mqtt_endpoint:latest
    network_mode: host
    restart: always
    command: ["uv", "run", "udp_forward", "192.168.0.102", "8888", "--listen_port", "9002"]
  udp_forward_estop:
    image: wamvtan/mqtt_endpoint:latest
    network_mode: host
    restart: always
    command: ["uv", "run", "udp_forward", "192.168.0.103", "4000", "--listen_port", "9003"]
