version: '3.4' # to use volumes type bind
services:
  l4t_opencv:
    build:
      context: .
      dockerfile: Dockerfile
      args:    
        - OPENCV_VERSION=4.5.0
    privileged: true
    container_name: l4t_opencv_container
    tty: true