services:
  l4t_opencv_builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:    
        - OPENCV_VERSION=4.5.0
        - BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.5.0
    privileged: true
    container_name: l4t_opencv_builder_container
    tty: true