name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rosdistro : [$parameter.rosdistro]
    steps:
      - name: Setup ROS2 ${{ matrix.rosdistro }} environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}
      - uses: actions/checkout@v2-beta
      - name: Copy repository
        run: |
            mkdir -p ~/ros2_ws/src
            cp -rf . ~/ros2_ws/src
        