---
- name: install qemu
  become: yes
  apt:
    name: "{{ packages }}"
    cache_valid_time: 3600
    update_cache: yes
  vars:
    packages:
      - qemu-user-static

- name: check jetson-nano-sd-card-image.zip exists
  stat:
    path: ../docker/docker_testbench/jetson-nano-sd-card-image.zip
  register: check_image_zip_exists

- name: download image
  get_url: 
    url: https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jeston_nano/jetson-nano-jp461-sd-card-image.zip
    sha256sum: 735fea3df2509436ce43e480f2e70d633f0adfe84007ed9ce7f43910e3814168
    dest: ../docker/docker_testbench/jetson-nano-sd-card-image.zip
    force: false
  when: not check_image_zip_exists.stat.exists

- name: check sd-blob-b01.img exists
  stat:
    path: ../docker/docker_testbench/sd-blob-b01.img
  register: check_image_exists

- name: unzip jetson-nano-sd-card-image.zip
  unarchive:
    src: ../docker/docker_testbench/jetson-nano-sd-card-image.zip
    dest: ../docker/docker_testbench
    remote_src: false
  when: not check_image_exists.stat.exists

- name: chmod image
  shell: chmod 777 ../docker/docker_testbench/mount_point
  become: true

- name: mount jetson image
  become: true
  shell: mount -o offset=$((512*28672)) ../docker/docker_testbench/sd-blob-b01.img ../docker/docker_testbench/mount_point
  ignore_errors: true

- name : start container
  become: yes
  shell : docker-compose up --build -d
  args:
    chdir: ../docker/docker_testbench/docker_compose
  environment:
    JETPACK_ROOT: "{{ansible_env.PWD}}/../docker/docker_testbench/mount_point/"