name: "Build auto logger image action"
description: "Build Virtual RobotX docker images"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: basic install
      run: |
          sudo apt install make ansible
    - uses: actions/checkout@v4
    - name: run ansible
      run: |
          ansible-playbook -i ansible/hosts/localhost.ini ansible/export_repos.yml --connection local --become -e ansible_user=ubuntu
    - name: copy repos file
      run: |
        cp ansible/mv ansible/packages_exact.repos .github/workflows/docker/auto_logger/
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/auto_logger
        file: ./.github/workflows/docker/auto_logger/Dockerfile
        tags: wamvtan/auto_logger:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/auto_logger:buildcache
        cache-to: type=registry,ref=wamvtan/auto_logger:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/auto_logger
        file: ./.github/workflows/docker/auto_logger/Dockerfile
        tags: wamvtan/auto_logger:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/auto_logger:buildcache
        push: false
    - uses: peter-evans/dockerhub-description@v3
      if: ${{ github.event_name == 'pull_request'}}
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        repository: wamvtan/auto_logger
        short-description: "Docker Image for Virtual RobotX Challenge"
        readme-filepath: ./.github/workflows/docker/auto_logger/README.md
        enable-url-completion: true
