---
- name: install mavros via apt
  become: yes
  apt:
    name: "{{ packages }}"
    cache_valid_time: 3600
    update_cache: yes
  vars:
    packages:
    - ros-humble-mavros
  tags: [setup_mavros]

- name: install GeographicLib datasets
  shell: ros2 run mavros install_geographiclib_datasets.sh
  tags: [setup_mavros]
  
- name: make workspace
  file: path={{workspace_path}}
        state=directory
  tags: [create_uav_workspace]

- name: make src dir from workspace_path
  file: path={{workspace_path}}/src
        state=directory
  tags: [create_uav_workspace]

- name: add setup.bash to .bashrc
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "source /opt/ros/humble/setup.bash"
    create: yes
  tags: [create_uav_workspace]

- name: add local_setup.bash to .bashrc
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "source {{ workspace_path }}/install/local_setup.bash"
    create: yes
  tags: [create_uav_workspace]