---
ros_package_name: ros-galactic-desktop
workspace_path: "{{ansible_env.PWD}}/../robotx_ws"
python_workspace_path: "{{ansible_env.PWD}}/../python_ws"
ansible_python_interpreter : "/usr/bin/python3"
ntp_server: true