name: "Build VRX image action"
description: "Build Virtual RobotX docker images"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/vrx
        file: ./.github/workflows/docker/vrx/Dockerfile
        tags: wamvtan/vrx:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/vrx:buildcache
        cache-to: type=registry,ref=wamvtan/vrx:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/vrx
        file: ./.github/workflows/docker/vrx/Dockerfile
        tags: wamvtan/vrx:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/vrx:buildcache
        push: false
    - name: Build Docker Image with cuda
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/vrx
        file: ./.github/workflows/docker/vrx/Dockerfile.cuda
        tags: wamvtan/vrx:latest_cuda
        no-cache: true
        push: ${{ github.event_name != 'pull_request'}}
    - uses: peter-evans/dockerhub-description@v3
      if: ${{ github.event_name == 'pull_request'}}
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        repository: wamvtan/vrx
        short-description: "Docker Image for Virtual RobotX Challenge"
        readme-filepath: ./.github/workflows/docker/vrx/README.md
        enable-url-completion: true
