name: "Build VRX image Action"
description: "Build Virtual RobotX docker images"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./.github/workflows/docker/vrx
        file: ./.github/workflows/docker/vrx/Dockerfile
        tags: wamvtan/vrx:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/vrx:buildcache
        cache-to: type=registry,ref=wamvtan/vrx:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./.github/workflows/docker/vrx
        file: ./.github/workflows/docker/vrx/Dockerfile
        tags: wamvtan/vrx:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/vrx:buildcache
        push: false