- name : clone librealsense
  git:
    repo: https://github.com/IntelRealSense/librealsense.git
    dest: ../librealsense
    version: master
    accept_hostkey: yes
- name: install depends
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - libssl-dev
      - libusb-1.0-0-dev
      - pkg-config
      - libgtk-3-dev
      - libglfw3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
  become: yes
- name: setup librealsense rule
  become: yes
  args:
    chdir: ../librealsense
  shell: echo y | ./scripts/setup_udev_rules.sh
- name: install librealsense
  become: yes
  args:
    chdir: ../librealsense
  shell: echo y | ./scripts/patch-realsense-ubuntu-lts.sh
  ignore_errors: yes
- name: build librealsense(cmake)
  args:
    chdir: ../librealsense
  shell: cmake .
- name: install librealsense(cmake)
  args:
    chdir: ../librealsense
  shell: make install
  become: yes