name: "Build Dev Container Action"
description: "Build dev-container docker images"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./.github/workflows/docker/dev_container
        file: ./.github/workflows/docker/dev_container/Dockerfile
        tags: wamvtan/dev_container:latest
        no-cache: true
        # cache-from: type=registry,ref=wamvtan/dev_container:buildcache
        # cache-to: type=registry,ref=wamvtan/dev_container:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./.github/workflows/docker/dev_container
        file: ./.github/workflows/docker/dev_container/Dockerfile
        tags: wamvtan/dev_container:latest
        no-cache: true
        # cache-from: type=registry,ref=wamvtan/dev_container:buildcache
        push: false