name: "Build dev-container image Action"
description: "Build dev-container docker images"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true
  base_image:
    description: "Base image"
    required: true
  image_name:
    description: "Docker image name"
    required: true
  entrypoint:
    description: "Name of the entrypoint.sh"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: copy ouxt_automation
      run: |
        cp -r . ./.github/workflows/docker/dev_container
      shell: bash
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/dev_container
        file: ./.github/workflows/docker/dev_container/Dockerfile
        tags: ${{ inputs.image_name }}:latest
        build-args: |
          BASE_IMAGE=${{ inputs.base_image }}
          ENTRYPOINT_SH=${{ inputs.entrypoint }}
        no-cache: true
        # cache-from: type=registry,ref=wamvtan/dev_container:buildcache
        # cache-to: type=registry,ref=wamvtan/dev_container:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/dev_container
        file: ./.github/workflows/docker/dev_container/Dockerfile
        tags: ${{ inputs.image_name }}:latest
        build-args: |
          BASE_IMAGE=${{ inputs.base_image }}
          ENTRYPOINT_SH=${{ inputs.entrypoint }}
        no-cache: true
        # cache-from: type=registry,ref=wamvtan/dev_container:buildcache
        push: false
    # - uses: peter-evans/dockerhub-description@v3
    #   if: ${{ github.event_name != 'pull_request'}}
    #   with:
    #     username: ${{ inputs.docker_username }}
    #     password: ${{ inputs.docker_password }}
    #     repository: ${{ inputs.image_name }}:latest
    #     short-description: "Docker Image for Robot Development"
    #     readme-filepath: ./.github/workflows/docker/dev_container/README.md
    #     enable-url-completion: true
