---
- name: install required packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - gnupg

- name: add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_18.x {{ ansible_lsb.codename }} main
    state: present
    update_cache: yes

- name: install nodejs
  apt:
    name: nodejs
    state: present
  become: true
