name: build image for YoloX

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  yolox:
    steps:
    name: build and push wamvtan/l4t_opencv
    runs-on: ubuntu-20.04
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        if: ${{ github.event_name != 'pull_request'}}
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: Dockerfile
          tags: wamvtan/yolox
          no-cache: true
          push: true