# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ground_station_heartbeat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ground_station_heartbeat.proto',
  package='protolink__ground_station_heartbeat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eground_station_heartbeat.proto\x12#protolink__ground_station_heartbeat\":\n\x18ground_station_heartbeat\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x0c\n\x04mode\x18\x02 \x01(\rb\x06proto3'
)




_GROUND_STATION_HEARTBEAT = _descriptor.Descriptor(
  name='ground_station_heartbeat',
  full_name='protolink__ground_station_heartbeat.ground_station_heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='protolink__ground_station_heartbeat.ground_station_heartbeat.sequence', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='protolink__ground_station_heartbeat.ground_station_heartbeat.mode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['ground_station_heartbeat'] = _GROUND_STATION_HEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ground_station_heartbeat = _reflection.GeneratedProtocolMessageType('ground_station_heartbeat', (_message.Message,), {
  'DESCRIPTOR' : _GROUND_STATION_HEARTBEAT,
  '__module__' : 'ground_station_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:protolink__ground_station_heartbeat.ground_station_heartbeat)
  })
_sym_db.RegisterMessage(ground_station_heartbeat)


# @@protoc_insertion_point(module_scope)
