# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardware_communication_msgs__HeartBeat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="hardware_communication_msgs__HeartBeat.proto",
    package="protolink__hardware_communication_msgs__HeartBeat",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n,hardware_communication_msgs__HeartBeat.proto\x12\x31protolink__hardware_communication_msgs__HeartBeat":\n&hardware_communication_msgs__HeartBeat\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x62\x06proto3',
)


_HARDWARE_COMMUNICATION_MSGS__HEARTBEAT = _descriptor.Descriptor(
    name="hardware_communication_msgs__HeartBeat",
    full_name="protolink__hardware_communication_msgs__HeartBeat.hardware_communication_msgs__HeartBeat",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="sequence",
            full_name="protolink__hardware_communication_msgs__HeartBeat.hardware_communication_msgs__HeartBeat.sequence",
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=99,
    serialized_end=157,
)

DESCRIPTOR.message_types_by_name[
    "hardware_communication_msgs__HeartBeat"
] = _HARDWARE_COMMUNICATION_MSGS__HEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

hardware_communication_msgs__HeartBeat = _reflection.GeneratedProtocolMessageType(
    "hardware_communication_msgs__HeartBeat",
    (_message.Message,),
    {
        "DESCRIPTOR": _HARDWARE_COMMUNICATION_MSGS__HEARTBEAT,
        "__module__": "hardware_communication_msgs__HeartBeat_pb2"
        # @@protoc_insertion_point(class_scope:protolink__hardware_communication_msgs__HeartBeat.hardware_communication_msgs__HeartBeat)
    },
)
_sym_db.RegisterMessage(hardware_communication_msgs__HeartBeat)


# @@protoc_insertion_point(module_scope)
