/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__GEOGRAPHIC_MSGS__GEOPOSE_PROTO_GEOGRAPHIC_MSGS__GEOPOSE_PB_H_INCLUDED
#define PB_PROTOLINK__GEOGRAPHIC_MSGS__GEOPOSE_PROTO_GEOGRAPHIC_MSGS__GEOPOSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint {
    double latitude;
    double longitude;
    double altitude;
} protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint;

typedef struct _protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion {
    double x;
    double y;
    double z;
    double w;
} protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion;

typedef struct _protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose {
    bool has_position;
    protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint position;
    bool has_orientation;
    protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion orientation;
} protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_init_default {false, protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_init_default, false, protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_init_default}
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_init_default {0, 0, 0}
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_init_default {0, 0, 0, 0}
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_init_zero {false, protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_init_zero, false, protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_init_zero}
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_init_zero {0, 0, 0}
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_latitude_tag 1
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_longitude_tag 2
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_altitude_tag 3
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_x_tag 1
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_y_tag 2
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_z_tag 3
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_w_tag 4
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_position_tag 1
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_orientation_tag 2

/* Struct field encoding specification for nanopb */
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  orientation,       2)
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_CALLBACK NULL
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_DEFAULT NULL
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_position_MSGTYPE protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_orientation_MSGTYPE protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion

#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          1) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         2) \
X(a, STATIC,   SINGULAR, DOUBLE,   altitude,          3)
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_CALLBACK NULL
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_DEFAULT NULL

#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x,                 1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y,                 2) \
X(a, STATIC,   SINGULAR, DOUBLE,   z,                 3) \
X(a, STATIC,   SINGULAR, DOUBLE,   w,                 4)
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_CALLBACK NULL
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_DEFAULT NULL

extern const pb_msgdesc_t protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_msg;
extern const pb_msgdesc_t protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_msg;
extern const pb_msgdesc_t protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_fields &protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_msg
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_fields &protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_msg
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_fields &protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_msg

/* Maximum encoded size of messages (where known) */
#define PROTOLINK__GEOGRAPHIC_MSGS__GEOPOSE_PROTO_GEOGRAPHIC_MSGS__GEOPOSE_PB_H_MAX_SIZE protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_size
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geographic_msgs__GeoPoint_size 27
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_geometry_msgs__Quaternion_size 36
#define protolink__geographic_msgs__GeoPose_geographic_msgs__GeoPose_size 67

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
