/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__HARDWARE_COMMUNICATION_MSGS__SIMPLEIMU_PROTO_HARDWARE_COMMUNICATION_MSGS__SIMPLEIMU_PB_H_INCLUDED
#define PB_PROTOLINK__HARDWARE_COMMUNICATION_MSGS__SIMPLEIMU_PROTO_HARDWARE_COMMUNICATION_MSGS__SIMPLEIMU_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu {
    double accel_x;
    double accel_y;
    double accel_z;
    double gyro_x;
    double gyro_y;
    double gyro_z;
} protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_init_default {0, 0, 0, 0, 0, 0}
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_init_zero {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_accel_x_tag 1
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_accel_y_tag 2
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_accel_z_tag 3
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_gyro_x_tag 4
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_gyro_y_tag 5
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_gyro_z_tag 6

/* Struct field encoding specification for nanopb */
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_x,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_y,           2) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_z,           3) \
X(a, STATIC,   SINGULAR, DOUBLE,   gyro_x,            4) \
X(a, STATIC,   SINGULAR, DOUBLE,   gyro_y,            5) \
X(a, STATIC,   SINGULAR, DOUBLE,   gyro_z,            6)
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_CALLBACK NULL
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_DEFAULT NULL

extern const pb_msgdesc_t protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_fields &protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_msg

/* Maximum encoded size of messages (where known) */
#define PROTOLINK__HARDWARE_COMMUNICATION_MSGS__SIMPLEIMU_PROTO_HARDWARE_COMMUNICATION_MSGS__SIMPLEIMU_PB_H_MAX_SIZE protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_size
#define protolink__hardware_communication_msgs__SimpleImu_hardware_communication_msgs__SimpleImu_size 54

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
