---
- name: Install GitHub Actions Runner
  hosts: all
  user: ansible
  become: yes
  vars:
    - github_account: wam-v-tan
    - runner_org: yes
  roles:
    - role: monolithprojects.github_actions_runner