---
- name: make workspace
  file: path={{workspace_path}}
        state=directory

- name: make src dir from workspace_path
  file: path={{workspace_path}}/src
        state=directory

- name: add setup.bash to .bashrc
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "source /opt/ros/galactic/setup.bash"
    create: yes

- name: add local_setup.bash to .bashrc
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "source {{ workspace_path }}/install/local_setup.bash"
    create: yes