name: "Build YOLOX image action"
description: "Build YOLOX docker images"

inputs:
  docker_username:
    description: "Username for Dockerhub"
    required: true
  docker_password:
    description: "Password for Dockerhub"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Build and Push Docker Image
      if: ${{ github.event_name != 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/yolox
        file: ./.github/workflows/docker/yolox/Dockerfile
        tags: wamvtan/yolox:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/yolox:buildcache
        cache-to: type=registry,ref=wamvtan/yolox:buildcache,mode=max
        push: true
    - name: Build Docker Image
      if: ${{ github.event_name == 'pull_request'}}
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        context: ./.github/workflows/docker/yolox
        file: ./.github/workflows/docker/yolox/Dockerfile
        tags: wamvtan/yolox:latest
        no-cache: false
        cache-from: type=registry,ref=wamvtan/yolox:buildcache
        push: false
