name: build_scenario_test_image

on:
  workflow_run:
    workflows:
      - export_repos
    types: [ completed ]

jobs:
  NotifyFailure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
    - uses: actions/download-artifact@v2
      with:
        name: packages.repos
        path: docker/scenario_test/packages.repos