name: build_firmware

on:
  pull_request:
    paths:
      - "firmware/**"
      - ".github/workflows/build_firmware.yaml"
  workflow_dispatch:

jobs:
  build_platformio_firmware:
    name: build_platformio_firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_directory:
          - "firmware/mini_v/estop_driver"
          - "firmware/mini_v/gnss_driver"
          - "firmware/mini_v/motor_driver"
        include:
          - project_directory: "firmware/mini_v/motor_driver"
            environment: "right"
          - project_directory: "firmware/mini_v/motor_driver"
            environment: "left"
          - project_directory: "firmware/mini_v/estop_driver"
            environment: "teensy41"
          - project_directory: "firmware/mini_v/gnss_driver"
            environment: "m5stack-cores3"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        working-directory: ${{ matrix.project_directory }}

      - name: Build PlatformIO Project
        run: pio run -e ${{ matrix.environment }}
        working-directory: ${{ matrix.project_directory }}

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ matrix.project_directory }}/.pio/build