name: build_scenario_test_image

on:
  workflow_run:
    workflows:
      - export_repos
    types: [ completed ]

jobs:
  NotifyFailure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
    - uses: actions/download-artifact@v2
      with:
        name: packages.repos
        path: docker/scenario_test/packages.repos
    - name: Build Docker Image
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        tags: latest
        no-cache: true
        build_args: BUILDKIT_INLINE_CACHE=1
        push: false