name: Publish ROS2 CI Base Image

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  ros2:
    name: Publish the Basic Image
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        rosdistro: [foxy, galactic]
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        if: ${{ github.event_name != 'pull_request'}}
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wamvtan/ros2-ci-base
          context: ./docker/ci-base
          file: Dockerfile.${{ matrix.rosdistro }}
          tags: ${{ matrix.rosdistro }}
          no-cache: true
          push: true
  perception-jetson:
    name: Publish the Basic Image
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        dockerfile: [[Dockerfile, galactic-ros-base-l4t-r32.6], [Dockerfile.trt801, galactic-ros-base-l4t-r32.6-trt]]
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        if: ${{ github.event_name != 'pull_request'}}
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wamvtan/ros
          context: ./docker/l4t-ros2-base
          file: ${{ matrix.dockerfile[0] }}
          tags: ${{ matrix.dockerfile[1] }}
          platforms: linux/arm64/v8
          no-cache: true
          push: true
