name: export_repos

on:
  schedule:
  - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  job1:
    name: setup
    runs-on: ubuntu-20.04
    steps:
      - name: basic install
        run: |
            sudo apt install make ansible
      - name: ansible version
        run: |
              ansible-playbook --version
      - uses: actions/checkout@v2-beta
      - name: ansible
        run: |
            ansible-playbook -i ansible/hosts/localhost.ini ansible/export_repos.yml --connection local --become -e ansible_user=ubuntu
      - uses: actions/upload-artifact@v2
        with:
          name: packages.repos
          path: ansible/packages.repos