name: integration_test

on:
  schedule:
  - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
    inputs:
      overwrite_package:
        required: false
        default: ''
        description: 'name of the package you want to overwrite'
      commit_hash:
        required: false
        default: ''
        description: 'commit hash of overwrite package'
  push:
    branches: [ master ]

jobs:
  export_repos_full:
    name: export_repos_full
    runs-on: ubuntu-20.04
    steps:
    - name: basic install
      run: |
          sudo apt install make ansible
    - name: ansible version
      run: |
            ansible-playbook --version
    - uses: actions/checkout@v2-beta
    - name: ansible
      run: |
          ansible-playbook -i ansible/hosts/localhost.ini ansible/export_repos_full.yml --connection local --become -e ansible_user=ubuntu
    - uses: OUXT-Polaris/update-repos-action@0.0.1
      with:
        input_repos_file: ansible/packages.repos
        output_repos_file: packages.repos
        package_name: github.event.inputs.overwrite_package
        target_version: github.event.inputs.commit_hash
    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: packages.repos
  build:
    name: build
    runs-on: ubuntu-20.04
    needs: export_repos_full
    steps:
    - uses: ros-tooling/setup-ros@v0.2
    - name: make workspace
      run: |
        mkdir -p robotx_ws/src
    - uses: actions/download-artifact@v2
      with:
        name: packages
        path: robotx_ws
    - uses: actions/cache@v2
      id: chache_workspace
      with:
        path: robotx_ws
        key: workspace
    - name: build packages
      run: |
        vcs import src < packages.repos
        rosdep update
        rosdep install -iry --from-paths src --rosdistro foxy
        source /opt/ros/foxy/setup.bash
        colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
      working-directory: robotx_ws

